### ISSUE TITLE
Sublists aren't parsed when indented with tabs

### ISSUE THREAD

**Issue by matheuss** [remarkjs/remark#198]
If you indent a sublist with `tabs`, they aren't parsed as lists.

Steps to reproduce:

```
git clone https://github.com/matheuss/remark-issue-198
cd remark-issue-198
npm i && node .
```

I'm happy to provide more info if needed ☺️

**Comment by wooorm** [comment]
Thanks, that’s very detailed, I appreciate that!

It’ll take a while before I can get to it though. I’m in the process of rewriting the parsing done by remark into a commonmark compliant parser, and a gfm parser. But it’s a lot of work 😬

**Comment by matheuss** [comment]
I would be happy to help, but I have no clue on how to start 😅 I'll try to dig into it sometime later today. 

Seems a lot of cool work 😛 Good luck!

**Comment by Rokt33r** [comment]
I found indent with double spaces also isn't be parsed properly.

It should be parsed as

**Comment by Rokt33r** [comment]
I found sublists with double spaces indent are not parsed too.
https://gist.github.com/Rokt33r/b6161f11fd5edf71ee2c4c74832297aa

**Comment by fbartho** [comment]
Is this issue still live?

I got burnt by it when enabling Prettier which uses remark under the hood! /ref: https://github.com/prettier/prettier/issues/3223

**Comment by craftzdog** [comment]
heads up

**Comment by transitive-bullshit** [comment]
@wooorm I'm trying to debug this and I think I've found the root cause.

Minimal repro case:
```js
const remark = require('../remark');
const inspect = require('unist-util-inspect');

const input1 = `- 123\n\t- 456`;
// const input2 = `- 123\n  - 456`;

node = remark()
  .data('settings', {})
  .parse(input1);

console.log(inspect(node));
```

With `input1`, `remark` incorrectly parses to:

```
root[1] (1:1-2:7, 0-12)
└─ list[1] (1:1-2:7, 0-12) [ordered=false][loose=false]
   └─ listItem[1] (1:1-2:7, 0-12) [loose=false]
      └─ paragraph[1] (1:3-2:7, 2-12)
         └─ text: "123\n\t\t- 456" (1:3-2:7, 2-12)
```

With `input2`, `remark` correctly parses to:

```
root[1] (1:1-2:8, 0-13)
└─ list[1] (1:1-2:8, 0-13) [ordered=false][loose=false]
   └─ listItem[2] (1:1-2:8, 0-13) [loose=false]
      ├─ paragraph[1] (1:3-1:6, 2-5)
      │  └─ text: "123" (1:3-1:6, 2-5)
      └─ list[1] (2:3-2:8, 8-13) [ordered=false][loose=false]
         └─ listItem[1] (2:3-2:8, 8-13) [loose=false]
            └─ paragraph[1] (2:5-2:8, 10-13)
               └─ text: "456" (2:5-2:8, 10-13)
```

This [line](https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/list.js#L435) is the crux of where the two diverge, and I've tried artificially changing the output for `input` to be the correctly trimmed lines, and the parsing result is then correct.

Specifically, for `input1`, instead of trimming the line `\t- 456`, the result is a non-trimmed line that introduces an **extra** tab `\t\t- 456`.

The `getIndent` and `removeIndent` logic is pretty esoteric. Would you mind giving me some advice as to how to proceed here?

Thanks!

**Comment by scinos** [comment]
Any update in this issue?

If nobody is working on it I may give it a go. Latest comment is ~2 years old, is their analysis still valid?

**Comment by transitive-bullshit** [comment]
@scinos I believe it's still valid and that nobody is currently working on this.
