### ISSUE TITLE
An escaped exclamation mark preceding a link ends up unescaped

### ISSUE THREAD

**Issue by antialiasis** [remarkjs/remark#371]
### Subject of the issue

remark-stringify seems to fail to escape exclamation marks in text nodes, even when this changes the meaning of the resulting Markdown.

### Your environment

Windows 10, remark 10.0.0, npm 6.1.0, node 10.7.0

### Steps to reproduce

Run

    remark().processSync('\\![example.com](https://www.example.com)').toString()

### Expected behaviour

I should get the same Markdown back: `\![example.com](https://www.example.com)`. In other words, an escaped textual exclamation mark, followed by a link to example.com.

### Actual behaviour

Instead, I get this:

    '![example.com](https://www.example.com)\n'

This is an image with the source https://www.example.com and the alt text example.com - not the same Markdown as I originally entered.

After some debugging I found that it's being parsed correctly (the syntax tree has a text node followed by a link node), but remark-stringify isn't escaping the exclamation mark when it compiles the text node.

**Comment by wooorm** [comment]
@antialiasis thanks for the detailed issue! 🎉 Even though it’s a bug, it’s nice to see such a good written issue 😉

This should probably go in [escape.js](https://github.com/remarkjs/remark/blob/master/packages/remark-stringify/lib/escape.js). Care to work on it? Let me know if I can help!

**Comment by antialiasis** [comment]
Thanks, I submitted a PR. I think it covers it, but let me know if it needs modification.

**Comment by arobase-che** [comment]
Hi,

This PR seems a little greedy since : 
```js
const r = remark().processSync('![not link\\](Link)').toString();
console.log(r);
console.log(remark().processSync(r).toString())
```
Yield : 
```
\!\[not link](Link)
!\[not link](Link)
```
At first it escape the bang and after a second processing, it no longer do.

Also : 
```js
console.log(remark().processSync('!<http://auto.link>').toString());
```
Will be escaped : 
```
\!<http://auto.link>
```
The bang before the auto-link is escaped. Technical, it's a bang before a link so the PR escaped it. But it's an auto-link and will not present any problem left unescaped.
_________________

I don't understand the purpose of : 
```js
        (character === exclamationMark &&
          value.charAt(position + 1) === leftSquareBracket) ||
```
In [remark-stringify](https://github.com/remarkjs/remark/commit/d4a8121b0d2f7c07fee49b1201cbe593d9e9cd47#diff-e4024287fef80033295c2d2417908d28R93)

Since the bracket will be escaped.
But it seems expected, they is a test about that : 
```js
t.equal(toString('![a'), '\\!\\[a', '`!` before `[`')
```
