### ISSUE TITLE
Empty list items interrupting a paragraph

### ISSUE THREAD

**Issue by duailibe** [remarkjs/remark#407]
### Subject of this issue

```md
foo
*

foo
+

foo
1.
```

### Expected behaviour

It should be parsed as 3 different paragraphs.

### Actual behaviour

`*`, `+` and `1.` are considered empty list items.

https://astexplorer.net/#/gist/72f98584a419e5cd19c28573229cf735/cafe6393c3e07f7c5b22ee2d9875564cd2b716ed

Caught this updating Prettier to `remark-parse@6.0.3`

**Comment by duailibe** [comment]
I'm willing to contribute to this, but I didn't see how I could check, inside the list tokenizer, if the lone marker is preceded by text or not.

**Comment by wooorm** [comment]
Hm, I do think it’s weird that CM seems to say that:

```
foo
*
```

Is one paragraph, but:

```
foo
*᛫
```

(where `᛫` is a space) is a paragraph followed by a list, and that:

```
foo

*
```

(no space) is also a paragraph followed by a list.

So I don’t think the problem is `.inParagraph`, because we:
- have interruptors
- lists can be made without a space
- lists can interrupt paragraphs
- but apparently lists can’t interrupt without a space 🤷‍♂️

Could you investigate if the CM spec says something about this?

**Comment by duailibe** [comment]
> Is one paragraph, but:
> 
> ```
> foo
> *᛫
> ```
> 
> (where `᛫` is a space) is a paragraph followed by a list

Is it? That's not what happens in dingus: https://spec.commonmark.org/dingus/?text=foo%0A*%20%0A*%20

What I could tell from the spec regarding empty items:
- it does not matter if there are spaces after the bullet marker (https://spec.commonmark.org/0.29/#example-252)
- an empty list item cannot interrupt a paragraph (https://spec.commonmark.org/0.29/#example-255)

**Comment by wooorm** [comment]
Ah, sorry, I must’ve added a blank line when testing that 🤔 Thanks for clarifying!

**Comment by wooorm** [comment]
This is now released in [`remark@13.0.0`](https://github.com/remarkjs/remark/releases/tag/13.0.0)
