### ISSUE TITLE
Support multiple `--ignore-path` for CLI

### ISSUE THREAD

**Issue by evilebottnawi** [remarkjs/remark#416]
### Subject of the feature

Support multiple `--ignore-path` flags for CLI.

### Problem

I have project where use `.gitignore` for ignore compiled files and have `vendor` directory where put some vendor stuff (copy/paste task), `vendor` directory contains markdown files, so using `remark . -i .gitignore` still linting vendor markdown files. 

### Expected behaviour

Ignore `vendor` files using multiple `--ignore-path`.

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

Creating `.remarkignore` and put `.gitignore` stuff and `!vendor` line in one file, but it is required to maintenance both files (`.gitignore` and `.remarkignore`), what is uncomfortable.

I know it is rare use case so i can send a PR.

**Comment by wooorm** [comment]
Hi again @evilebottnawi! Thanks for contributing.

This is more of an issue with the engine than here, but also: I believe https://github.com/unifiedjs/unified-engine/pull/40 solves it! That’s going to be released here soon. Would you agree?

**Comment by evilebottnawi** [comment]
@wooorm and yes and no, yes it is solve my problem, but my original request about multiple --ignore-path, it is allow to keep configuration for ignore in files, not in script

**Comment by wooorm** [comment]
Hmm. There are several other solutions:

1. The one I mentioned above
2. Use `.remarkignore` files. The closest detected ignore file is used. So place one in `$cwd/vendors/`, and one in `$cwd/`. You can also symlink `$cwd/.gitignore` to `$cwd/.remarkignore`
3. Don’t use ignore files, but instead pass globs to the files you want: `remark readme.md docs/**/*.md` instead of `remark .`

The reason that only one given file is supported, is that the patterns inside that given file are resolved from `$cwd`. So if multiple given files were supported, they would all be resolved from the same location, and that doesn’t make sense. Found files are resolved from the directory they exist in, so those are different.

The current workings match ESLint: it also allows only one given ignore file. I think this makes sense. And because there are so many other solutions, I don’t see a need in changing it.

**Comment by evilebottnawi** [comment]
> The one I mentioned above

Require keep two files with same ignore content, you can accidentally forgot update other file when you add something to ignore.

> Use .remarkignore files. The closest detected ignore file is used. So place one in $cwd/vendors/, and one in $cwd/. You can also symlink $cwd/.gitignore to $cwd/.remarkignore

Don't know what is is possible, sounds good, only one note - it will potentials create many ignore files in directories, My projects has many copy/paste vendor and own files (in one directory i can have ignored and nonignored file), but for me it is not look very bad.

> Don’t use ignore files, but instead pass globs to the files you want: remark readme.md docs/**/*.md instead of remark .

I prefer blacklist strategy - lintting all, except something, when other developers adding something in other directory/directories it does not require modify glob

> The current workings match ESLint: it also allows only one given ignore file. I think this makes sense. And because there are so many other solutions, I don’t see a need in changing it.

They have issue about this, but nobody starts with, so it was closed due inactivity

**Comment by wooorm** [comment]
> > The one I mentioned above
> 
> Require keep two files with same ignore content, you can accidentally forgot update other file when > you add something to ignore.

Ah, with [the one above](https://github.com/remarkjs/remark/issues/416#issuecomment-509834230) I meant extra ignore patterns. So still one file, but patterns passed in on the CLI. That has a different “problem”, but not keeping two files in sync.

> I prefer blacklist strategy - lintting all, except something, when other developers adding something in other directory/directories it does not require modify glob

OK!

> Don't know what is is possible, sounds good, only one note - it will potentials create many ignore files in directories, My projects has many copy/paste vendor and own files (in one directory i can have ignored and nonignored file), but for me it is not look very bad.

I think this is the way to go. How you do it depends on your directory structure. [Here’s how you can get support](https://github.com/remarkjs/.github/blob/master/support.md).

---

I’ll close this, because I think there’s so many ways to ignore files already that you can achieve what you want in several ways already. And I’m not happy with multiple ignore files as I mentioned [here](https://github.com/remarkjs/remark/issues/416#issuecomment-510043251).

Thanks for the issue and contributing though! 👍

**Comment by evilebottnawi** [comment]
@wooorm anyway support multiple `--ignore-path` aws requested in prettier/stylelint/eslint, no one has yet implemented, but there are many discussions, maybe we can revisit this in future

**Comment by wooorm** [comment]
Sure, sounds good!

**Comment by evilebottnawi** [comment]
@wooorm also i faced with strange behaviour:
```
remark . '!**/fixtures/**' -i .gitignore -f -q
```

stylelint/eslint/prettier supports multiple patterns, looks remark - no, should i open new issue for this?

**Comment by wooorm** [comment]
These are different problems with a different project. Namely unified-args or unified-engine.

> `remark . '!**/fixtures/**' -i .gitignore -f -q`

The second “pattern” is not supported. Instead, use `--ignore-patterns` or [`ignorePatterns`](https://github.com/unifiedjs/unified-engine/blob/master/doc/options.md#optionsignorepatterns).
unified does support multiple patterns. But it does not support negated patterns in patterns. For more information why negated patterns don’t make sense, see [glob](https://github.com/isaacs/node-glob#comments-and-negation).

> doesn't ignore node_modules even node_modules in .gitignore

Ignore files and ignore patterns work when searching for directories. To avoid confusion, they don’t work with glob patterns matching files. As in that case they are explicitly passed in *and* explicitly ignored..

**Comment by evilebottnawi** [comment]
> The second “pattern” is not supported. Instead, use --ignore-patterns or ignorePatterns.
unified does support multiple patterns. But it does not support negated patterns in patterns. For more information why negated patterns don’t make sense, see glob.

hm, looks you right, i think `unified` uses globby package for this case (he uses `fast-glob` instead original `glob` what is very fast, much faster than the original glob)

> Ignore files and ignore patterns work when searching for directories. To avoid confusion, they don’t work with glob patterns matching files. As in that case they are explicitly passed in and explicitly ignored..

It is strange, because stylelint/eslint works fine with same example

**Comment by wooorm** [comment]
> hm, looks you right, i think unified uses globby package for this case (he uses fast-glob instead original glob what is very fast, much faster than the original glob)

What does unified use? 🤔 and who is “he”? 🤷‍♂️

> It is strange, because stylelint/eslint works fine with same example

I don‘t think ESLint supports this, I can’t find any code for it.
The reason for not including it is described shortly [here](https://github.com/unifiedjs/unified-engine/pull/40#issue-288424561).

**Comment by evilebottnawi** [comment]
@wooorm 

> What does unified use? thinking and who is “he”? man_shrugging

globby use `fast-glob` now, not `node-glob`, i thought what packages under `remark-cli` use `globby` package for glob patterns. 

> I don‘t think ESLint supports this, I can’t find any code for it.

```
 eslint --ignore-path .gitignore '**/*.js'
```

no reports about `js` files inside `node_modules`

**Comment by AlexWayfer** [comment]
I believe the `.gitignore` should be ignored by default.
