### ISSUE TITLE
remark-cli: --quiet and --silent still output the file content

### ISSUE THREAD

**Issue by silvenon** [remarkjs/remark#489]
### Subject of the issue

I don't know if I misunderstood `--quiet` and `--silent` in remark-cli, but the file content is still being output, I don't know how to show only warnings and errors.

### Your environment

*   **OS**: macOS 10.15.4
*   **Packages**:
    - remark 12.0.0
    - remark-cli 8.0.0
*   **Env**:
    - node 13.7.0
    - yarn 1.22.4

### Steps to reproduce

```
remark --quiet path/to/file.md
remark --silent path/to/file.md
```

### Expected behaviour

I expected to only see warnings and/or errors for the given file.

### Actual behaviour

They are still preceded by the entire output of the file.

**Comment by ChristianMurphy** [comment]
This has tripped me up before as well.
IIRC `unified-args`/`remark-cli` needs the `--no-stdout` option as well to prevent the file from being output.

Thoughts on `--quiet` and `--silent` switching `--no-stdout` on by default @wooorm ?

**Comment by wooorm** [comment]
Ah yeah, I get that that’s a bit confusing.

To not output to stdout: pass in a glob, multiple files, `-o, --output`, or `--no-stdout`!

unified is both a linter like ESLint and a formatter like Prettier. Things that generate, such as Prettier or Browserify, typically output to stdout if they’re not specified to write to some place, and our behavior matches that (I’d say we’re a bit nicer: we don’t output if there (could) be multiple files). We do provide options to hide either the checking, or the generation, parts.

I think there’s also a use case to use `--quiet` or `--silent` to silence messages, but still want to output to stdout (e.g., you have a remarkrc that defines how to process and check content, but in a certain script you don’t want warnings, just: `remark -S < some program > some place`).

**Comment by wooorm** [comment]
Seems like this case is also expressly where you *don’t* want quiet / silent, so merging quiet and no-stdout wouldn’t solve this confusion.

**Comment by silvenon** [comment]
`--no-stdout` kinda made sense when I saw what it means, but I didn't try it before because stdout refers to _all_ output. Maybe at least extend the description of this option?

**Comment by wooorm** [comment]
> stdout usually refers to *all* output

Interesting! What makes you say that? Is there an example of a project that behaves like that?

---

Shells typically use stdout and stderr. For example, if you’re using curl, you’ll see informational messages, and the output together. If you do `curl example.com > output.html`, then you’ll still see information messages, but the output will go to `output.html`. That works because with `>`, only stdout is going to that place, whereas stderr remains. We’re doing the same here!

---

Re: update the description, the current is:

https://github.com/unifiedjs/unified-args/blob/40f8e4286a83e2f26d9b57586f8e154c1ca1bf6c/lib/schema.json#L134

Do you have a suggestion that would make it more clear?

**Comment by silvenon** [comment]
> Interesting! What makes you say that?

Ok, I obviously have some misconceptions about how shell works, so I'm closing this. This complexity is inherent to remark-cli acting both as a compiler and a linter.
