### ISSUE TITLE
remark-parse: Put a simple example pleaseee

### ISSUE THREAD

**Issue by stevemarksd** [remarkjs/remark#492]
### Subject of the feature

Simple example

### Problem

I want to quickly pick it up and use it. I'm currently reading through so many docs to figure out how to convert markdown to ast... The example you give me in the readme https://github.com/remarkjs/remark/tree/master/packages/remark-parse#api 

```
var unified = require('unified')
var createStream = require('unified-stream')
var markdown = require('remark-parse')
var remark2rehype = require('remark-rehype')
var html = require('rehype-stringify')

var processor = unified()
  .use(markdown, {commonmark: true})
  .use(remark2rehype)
  .use(html)

process.stdin.pipe(createStream(processor)).pipe(process.stdout)
```

I have no no idea what is going to pipe! Is it ast, is it html? Why would I care about html when I'm looking at remark-parse? (also the import names are super confusing when reading the `use()` chains). I just want ast, now I need to go read unified docs about how to get ast. This step just proves that the readme was not useful.

 - So now I search on google `unified markdown to ast`. Goes to https://github.com/remarkjs/remark . Not useful again because links me back to remark-parse.
 - Second result https://github.com/unifiedjs/unified nothing interesting, just home page of unified...
 - 3th result https://remark.js.org/ , interesting I see an example.... but jezz is using 'remark' not this library... ok. 2nd example, again same as this readme, straight to html. No AST
 - 4th result https://css-tricks.com/how-to-modify-nodes-in-an-abstract-syntax-tree/ ok! `const contents = unified()
	.use(markdown)
  .use(() => tree => console.log(JSON.stringify(tree, null, 2)))` actually console logs the ast. So ast is inside the `use`. I can try to hack it together by adding a callback on the `use`, but doesn't feel right. Still pissed that I need to use an extra library `unfied` just for sakes... Then need to use `processSync` to get from a file... Ok, I will put my md in a file then.

Ok, look at the source code:

```
function parse(options) {
  var settings = this.data('settings')
  var Local = unherit(Parser)

  Local.prototype.options = xtend(Local.prototype.options, settings, options)

  this.Parser = Local
}

```

I try 
```

import * as Parser from 'remark-parse'
const parser = new Parser({commonmark: true})
const ast = parser.Parser.process(md)
```

Error:

```
TypeError: this.data is not a function
```

What? I need a `.data` prop that is a function...

I look at `parser.js`... oh crap... I don't want to go sooooo deeeep, especially if is undocumented.

I go back to the `css-tricks` (see the irony in this name, I'm checking markdown related issues in a css website lol). Ok, I end up with:

```
const contents = unified()
  .use(markdownParser, {commonmark: true})
  .use(() => tree => console.log(JSON.stringify(tree, null, 2)))
  .processSync(fs.readFileSync('test.md'))
  .toString()
```

Of course, it won't work because needs a compiler: `Error: Cannot `processSync` without `Compiler``!!! Now I need to go back to unify to read some docs... how to get around without compiler (or should I run the compiler for sakes!)

I go back to my google search, top 10 results nothing useful.

I find https://www.npmjs.com/package/@textlint/markdown-to-ast somehow. Just look at their example!!!

```
var parse = require("@textlint/markdown-to-ast").parse;
var markdown = "It's a *text*";
var AST = parse(markdown);
```

Can you believe! one liner? no extra deps??? Of course I can't use it because the node types are capitalized (`Header` instead of `header`).... why?

I go back to unified docs.

Reading https://github.com/unifiedjs/unified#contents ... nothing catches my eye.. then after reading each one I see `var tree = unified().use(markdown).parse('# Hello world!')` wow!!! Jackpot.

```
const contents = unified()
  .use(markdownParser, {commonmark: true})
  .parse('# Hello world!')
console.log(contents)
```

and here you go a long time after, I even forgot why I need this library for... I know you want me to read all docs and understand unified and everything and all the ecosystem... 

```
{
  type: 'root',
  children: [
    {
      type: 'heading',
      depth: 1,
      children: [Array],
      position: [Position]
    }
  ],
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 1, column: 15, offset: 14 }
  }
}
```

Just see my frustration... I'm not a pro in unified or remark ecosystem. Just a web developer doing other web stuff and for years.

You might limit a lot the range of people that will use this library if it's so hard to start.

### Expected behaviour

I should be able to use it in 5 minutes.

### Alternatives

Why not put a dumb example like this?

```
import remarkParse from 'remark-parse';

const md = `# Title

Paragraph`

const ast = remarkParse(md);
// ast = [{...whatever it is...}]
```

**Comment by ChristianMurphy** [comment]
@stevemarksd Thanks for the feedback, pull requests to improve the documentation are welcome!

Some additional context:

"How to do X with Y" is a pretty common question in Unified.
This is what the Recipes on https://unifiedjs.com/learn are for.
If you have a specific use case to share, adding a recipe is welcome!

As for the _readme_, enumerating and documenting every possible combination isn't feasible, and documenting many use-cases in the _readme_ isn't a good experience because the _readme_s don't have a good search experience in the way a website can.
We've opted for a simple runnable example in each readme, and a recipes section on the website where folks can contribute other use-cases.

---

As for the example not being "simple".
Most people don't want to go just from Markdown to AST ([including yourself](https://spectrum.chat/unified/rehype/hi-how-to-simply-use-rehype-react-without-all-the-ton-of-dependencies~2462185e-75d5-4118-870c-a5d3d6b9cb62)).
They want to from Markdown to AST to something else, and that is what the _readme_ shows.

**Comment by wooorm** [comment]
The example you’re looking for is:

```js
var unified = require('unified')
var markdown = require('remark-parse')

var processor = unified().use(markdown)

var tree = processor.parse(document)
```

The readme, your first search hit, points to unified, your second search hit, which [includes this example](https://github.com/unifiedjs/unified#processorparsefile).

---

Steve. I get that it’s confusing. The unified collective contains hundreds of projects, which combined do infinity different things. We can’t describe all those things in one readme and have it be “simple”.
We get tons of people like you, who need a hand, and ask questions. And we gladly provide that. We don’t owe you, or anyone else, anything: we do it, for free, instead of hanging out with our friends and family or doing other things, because we like helping people!
But there is a big difference between how other people ask questions, and the aggressiveness showing in your posts: you’re getting free ice cream and complaining about it.

**Comment by stevemarksd** [comment]
@wooorm I think you are missing out on the purpose of my post. I know is free, I appreciate that, but if you have more people using it, I'm sure you'd be more happy. That's why I'm trying to explain my frustration trying to use it. I'm sure more people have the same problem, but they will just give up before even speaking up.

If you think the docs are good enough, I understand. But I would strongly suggest to add some docs for this project, not for other projects that work with this one. As you can see, it took me ages to find what I needed. Maybe yes, I was a bit frustrated so my tone was not the nicest one, but I just couldn't understand why someone don't want to make their project simpler. 

I also understand my usage is not common, but basic building blocks should be explained before going to the higher level. I'm not a genius :) And most of the people are not a genius.

I'm happy to do a PR to improve the docs if you guys let me.

**Comment by ChristianMurphy** [comment]
@stevemarksd Again, we understand and sympathize.
You've missed the point both @wooorm and I are making, there is a difference between venting your frustration at the people trying to help you, and asking questions or offering constructive feedback.
Your tone has been and continues to be aggressive and patronizing, tone it way down.

> I just couldn't understand why someone don't want to make their project simpler.

That hasn't been suggested in the conversations we've had.
You're getting very frustrated at a straw man, and being mean to the maintainers instead.

> Building blocks should be explained before going to the higher level.

Agreed, that is what https://unifiedjs.com/learn is for, any why it is linked to by most of the unified projects.
Additional guides and recipes are welcome!

> I'm happy to do a PR to improve the docs

Again, pull requests are welcome!
They don't need an issue to be opened.
