### ISSUE TITLE
special characters (square brackets) parsing issue

### ISSUE THREAD

**Issue by rjoydip** [remarkjs/remark#496]
### Subject of the issue

Parsing special characters (square brackets) issue on heading

### Your environment

*   **OS**: windows
*   **Packages**: react-markdown
*   **Env**: yarn (node 10+)

### Steps to reproduce

Original issue https://github.com/denoland/deno_website2/issues/562

Example: https://codesandbox.io/s/react-markdown-issue-with-square-brackets-36y0u

### Expected behaviour

Parser should show output `status.code[code]`

### Actual behaviour

Parser should show the output `status.codecode`

**Comment by ChristianMurphy** [comment]
[react-remark 4.3.1 uses `remark-parse` 5.](https://github.com/rexxars/react-markdown/blob/2d991aa1097e95064f0209fc6d3a15b6300c07c7/package.json#L45)
However the bug also appears in `remark-parse` 8. https://astexplorer.net/#/gist/19b827f79b4f3b8032c7937727540958/8060061985dedaf4e717d757b07030e1b868291e

commonmark defines the expected behavior as https://spec.commonmark.org/dingus/?text=status.code%5Bcode%5D

**Comment by wooorm** [comment]
@rjoydip What do you expect would happen if, for example, emphasis was in the heading? `some.code*emphasis*`?

…because that’s sort of what’s going on, the square braces make it into a link reference. If someone adds a definition to `[code]: https://example.com` later, it would turn into an actual link later.

You could also escape them, if you don’t want that. That’s what the Node docs ended up doing:

```markdown
### console.log(\[stuff])
```

**Comment by rjoydip** [comment]
@wooorm Thanks for addressing. Actually I saw that github is able to parse `status.code[code]` definition. But while using remark-parser it's not able to parse. I was just wondering that whether this is valid issue and `remark-parse` can parse it? Even `commonmark` expected the behavior.

Thanks @ChristianMurphy shared those references.

**Comment by wooorm** [comment]
I don’t think what I intended to say came across.

remark cares that you have link references in your heading. For your commonmark example, here is what I tried to show: https://spec.commonmark.org/dingus/?text=status.code%5Bthis%5D%0A%0Astatus.code%5Bthat%5D%0A%0A%5Bthat%5D%3A%20http%3A%2F%2Fexample.com. `linkReference`s exist in the AST. And they must be handled when serializing

What you are looking for, is handling the `linkReference`, such as like so:

```js
const renderers = () => ({
  heading: HeadingRenderer,
  linkReference: (props) => {
    const content = React.Children.toArray(props.children)
    if (props.href) {
      return <a href={props.href}>{content}</a>
    } else {
      return <>[{content}]</>
    }
  }
});
```

...however, I strongly believe you are trying to solve things that are solved already! You are linking headings, and you are slugging heading. I believe a better solution would be to use unified, such as like so, replacing most of your code:

```js
import React from 'react'
import ReactDOM from 'react-dom'
import unified from 'unified'
import markdown from 'remark-parse'
import remark2rehype from 'remark-rehype'
import slug from 'rehype-slug'
import autolink from 'rehype-autolink-headings'
import rehype2react from 'rehype-react'

var processor = unified()
  .use(markdown)
  .use(remark2rehype)
  .use(slug)
  .use(autolink)
  .use(rehype2react, {createElement: React.createElement})

function App() {
  return (
    <div className="App">
      {processor.processSync(input).result}
    </div>
  );
}
```

See also:
- https://github.com/rehypejs/rehype-slug
- https://github.com/rehypejs/rehype-autolink-headings

**Comment by rjoydip** [comment]
@wooorm It works. Thanks 👍
