### ISSUE TITLE
stringify: zero-width space HTML character entity replaced by Unicode

### ISSUE THREAD

**Issue by spl** [remarkjs/remark#518]
### Subject of the issue

It seems like `remark-stringify` is replacing my [zero-width space][wikipedia] (`&ZeroWidthSpace;` or `&#x200B;`) with the Unicode character. I'd prefer not to have that happen in case somebody edits the file in a text editor that doesn't make it evident that there is zero-width space.

[wikipedia]: https://en.wikipedia.org/wiki/Zero-width_space

### Your environment

*   **OS**: macOS Mojave (10.14.6)
*   **Packages**: `remark-stringify` 8.1.1
*   **Env**: `npm` 6.14.5, `node` v14.4.0

### Steps to reproduce

Run this file with `node`:

```js
require('unified')()
  .use(require('remark-parse'))
  .use(require('remark-stringify'))
  .process('zero&ZeroWidthSpace;width&ZeroWidthSpace;space', function (err, file) {
    console.error(require('vfile-reporter')(err || file))
    console.log(String(file))
  })
```

I look at the output with `vim`, which shows the zero-width space. You might be able to [`grep` for it][grep].

[grep]: https://superuser.com/questions/808716/linux-shell-command-to-grep-unicode-character-zero-width-space-u200b

### Expected behaviour

I would like to see the output:

```
zero&ZeroWidthSpace;width&ZeroWidthSpace;space
```

### Actual behaviour

But I see the output:

```
zero​width​space
```

(~~I don't know what GitHub's markdown renderer will do here.~~ Update: It looks like GitHub preserves the zero-width space.)

**Comment by spl** [comment]
I found GH-498, which seems related, but I thought a new issue should be created.

**Comment by wooorm** [comment]
To confirm, the “Actual behavior” your seeing from remark *does* include the unicode characters for zwsp, but you were expecting character references?

**Comment by spl** [comment]
> To confirm, the “Actual behavior” your seeing from remark _does_ include the unicode characters for zwsp, but you were expecting character references?

Yes, that's correct.

**Comment by wooorm** [comment]
Alright, in that case, everything “works”, but it’s not as visible as you’d expect.

We used to somewhat support that, indeed, but it was broken and I no longer believe it’s needed. I think we’ve left the ASCII world and are now living in a unicode world (more so than 11 years ago when Markdown was created, or how many years since HTML was created?)

In the input, we treat character references, character escapes, and literal characters the same. That’s the *A* in AST: it’s abstract, meaning unneeded information is lost, compared to a CST. We don’t track if `"` or `'` was used either, which makes the syntax tree usable. So doing this would also be rather hard / impossible.

I think the current behavior is fine. Could you educate folks on unicode characters instead? Encourage them to use extensions that show hidden characters?

**Comment by spl** [comment]
I agree that, for the most part, different representations of Unicode code points/characters can be considered the same. But, for practical purposes (such as this), I think zero-width spaces (and perhaps a few others) should probably be considered exceptions.

That said, I tried `s/&ZeroWidthSpace;/<!---->/`, and it seems that `remark-stringify` preserves the HTML comment, `<!---->`, which suits my purpose.

**Comment by noomorph** [comment]
@wooorm any idea if this can be solved by using https://github.com/syntax-tree/mdast-util-to-markdown/blob/main/lib/unsafe.js for my custom character set? Thanks in advance! 🙏

**Comment by wooorm** [comment]
This is not a bug that needs solving.

If you have questions, could you open a discussion rather than commenting on old closed issues?
But: `unsafe` might do what you want, not sure. Have you tried it? And I don’t know what you mean by “custom character set”
