### ISSUE TITLE
Settings - remove position properties no longer works

### ISSUE THREAD

**Issue by jeffsee55** [remarkjs/remark#540]
### Unable to remove position properties of ast in the latest release

Following [this example](https://github.com/unifiedjs/unified#example-1) things work as expected prior to the latest release, however I'm not getting the positional properties again after upgrading to remark-parse 9.0.0.

I've confirmed it works as expected on `v8.0.3`

```js
  var tree = unified()
    .use(markdown)
    .use({ settings: { position: false } })
    .parse(contents)

// yields 
// {...,
// position: {
//   start: { line: 1, column: 1, offset: 0 },
//   end: { line: 1, column: 17, offset: 16 }
// }
```

From reading about micromark I don't see  an option for this so I'm wondering if this would be supported without a plugin now 🤔 

### Your environment

*   **OS**: Mac 10.15.6
*   **Packages**:  `"remark-parse": "^9.0.0", "unified": "^9.2.0"`
*   **Env**:  `node v12.16.0`, `yarn 2.1.1`

**Comment by ChristianMurphy** [comment]
@jeffsee55 `position` is not part of the v9 options.
You can find a list of options here: https://github.com/syntax-tree/mdast-util-from-markdown#api
If you want to remove position in v9, I'd suggest using https://github.com/syntax-tree/unist-util-remove-position

**Comment by jeffsee55** [comment]
Thanks @ChristianMurphy - I had seen that but was wondering if the docs might be updated to reflect what's no longer possible. I would be happy to help make that change but it's sort of confusing since those docs are in the unified repo.

**Comment by ChristianMurphy** [comment]
> I had seen that but was wondering if the docs might be updated to reflect what's no longer possible

There are a lot of docs out there, unified has 300+ repos across 5+ different orgs, I'm not sure which specific docs you are referring to :sweat_smile: 

The documentation I linked to is up-to-date.
If there is another document which shows an outdated option, a PR to update it would be welcome :+1:

**Comment by jeffsee55** [comment]
Thanks @ChristianMurphy, I was referring to the docs from the link I provided above - It's in the [unified project repo](https://github.com/unifiedjs/unified#example-1). But I see that perhaps their docs are making a more generic comment and possibly doesn't apply specifically to `remark-parse`, though it did prior to 9.0.0. At any rate there's also no mention of this in the [release notes](https://github.com/remarkjs/remark/releases/tag/13.0.0) which is something I'm not able to edit obviously.

**Comment by wooorm** [comment]
remark has indeed supported position for ages I believe, but it’s also never documented it. I can’t find it in any official docs in the [last 4 years](https://github.com/remarkjs/remark/tree/remark-parse%401.0.0/packages/remark-parse). But I do remember having it in there before externalising it to [`unist-util-remove-position`](https://github.com/syntax-tree/unist-util-remove-position) in 2016. A couple plugins still used it in their test suites from before that time. I removed it because there is a utility that does it better, and didn’t add it to release notes because it was never documented as existing in the first place.

The example in the unified docs is an abstract processor, dealing with plugins which are called `pluginF` and such, it doesn’t refer to remark in any way. I don’t know how you come to the conclusion from that example that remark supports it? So that’s interesting! Or did you get it from somewhere else?
