### ISSUE TITLE
Inline only Markdown?

### ISSUE THREAD

**Issue by mooyoul** [remarkjs/remark#552]
### Subject of the feature

Inline-only Markdown parser

### Problem

I'd like to render inline-only markdown to HTML like Slack's message formatting.
Currently, There's no easy way to achieve this goal without traversing AST and feed nodes to specific stringifiers (e.g. remark-html or markdown-stringify).

Recently, [marked added this functionality](https://github.com/markedjs/marked/pull/1761).

But since i fall in love with ecosystem/vision of unified. I hope to get same functionality with remark.

### Expected behavior

Users should be able to render inline markdown only.

For example, When input is:

```markdown
## Heading

Hello **world**. This is a paragraph.
```

Should be rendered to html as:

```html
## Heading<br>
<br>
Hello <strong>world</strong>. This is a paragraph.<br>
```

### Alternatives

Maybe disallow specific Markdown syntax would be another option, but i think it is too complex solution.

**Comment by ChristianMurphy** [comment]
Interesting :thinking: 
In terms of desired outcome it looks like what is wanted is only some markdown becoming HTML, while other parts would stay markdown?

It may be possible to do from the remark side, updating https://github.com/zestedesavoir/zmarkdown/tree/HEAD/packages/remark-disable-tokenizers#readme to support the latest version.
However, it may be easier to do this from https://github.com/remarkjs/remark-rehype by customizing the https://github.com/syntax-tree/mdast-util-to-hast#optionshandlers option, to only translate block elements to HTML.

**Comment by wooorm** [comment]
> I'd like to render inline-only markdown to HTML like Slack's message formatting.

But Slack supports fenced code and lists? 🤔

> ```html
> ## Heading<br>
> <br>
> Hello <strong>world</strong>. This is a paragraph.<br>
> ```

Where should those `<br>`s come from?

> However, it may be easier to do this from https://github.com/remarkjs/remark-rehype by customizing the https://github.com/syntax-tree/mdast-util-to-hast#optionshandlers option, to only translate block elements to HTML.

For the website of unified, we do render `description`s of projects (github repos) and packages (npm packages). I defined a [strict schema for hast-util-sanitize](https://github.com/unifiedjs/unifiedjs.github.io/blob/f03d8cf713d50d9ca692ae300f9135d93bb9bce1/generate/pipeline/description-schema.js) to strip out tags for blocks and such. So block parsing would still be done, but the syntax ignored. You’d get (I believe):

```html
Heading

Hello <strong>world</strong>. This is a paragraph.
```

**Comment by wooorm** [comment]
@mooyoul What do you think of the ideas in these comments?

**Comment by ocavue** [comment]
> However, it may be easier to do this from https://github.com/remarkjs/remark-rehype by customizing the https://github.com/syntax-tree/mdast-util-to-hast#optionshandlers option, to only translate block elements to HTML.

This will not work for those who only want the AST instead of HTML. 

---

> You’d get (I believe):
> 
> ```html
> Heading
> 
> Hello <strong>world</strong>. This is a paragraph.
> ```

The output removed the `## `, which should be some plain text instead of a mark for heading if we only have inline markdown. Quote block and list item block have similar problems.

---

> Maybe disallow specific Markdown syntax would be another option.

@wooorm Do you think it's complicated to add this feature to `micromark`? And if the cost is reasonable, how do you think this feature should be added? I'd really like to have this feature so maybe I can implement it with some help.

**Comment by wooorm** [comment]
> This will not work for those who only want the AST instead of HTML.

hast is still an ast, and you can turn it back into mdast. Or you could do your own filtering of nodes.

> The output removed the `## `, which should be some plain text...

Can you expand more on why you want to turn off “tokenizers” / constructs? What is the use case for allowing folks to add markdown, but disallowing `* foo`?

> Do you think it's complicated to add this feature to micromark? [...] how do you think this feature should be added

Fairly complicated to do properly.

Note that if you actually only want “inlines”, you can [copy/paste micromark’s core (16 lines)](https://github.com/micromark/micromark/blob/ce4c1dcee73b43c147d5043aa89c9db9787c44db/lib/index.js#L1), and replace `document()` with `text()`. But: this will probably crash if there are for example blank lines in your markdown, because those can’t exist inline.

I also have to look into this in the next couple months, because MDX for example has to turn of HTML in text (inline) and flow (blocks).
Here’s how constructs work: https://github.com/micromark/micromark/blob/ce4c1dcee73b43c147d5043aa89c9db9787c44db/lib/constructs.js#L23.
But what’s even more complex is that MDX turns of indented code, [but there are many places that expect indented code to be there](https://github.com/micromark/micromark/search?q=tabSize+path%3Alib).
A similar difficult case is [lists vs. thematic breaks](https://github.com/micromark/micromark/blob/ce6b8cf63a98f5a54237907f028e676ae2b9ae7e/lib/tokenize/list.js#L49)

**Comment by ocavue** [comment]
> hast is still an ast, and you can turn it back into mdast.

I didn't know that before. Thanks to mentioning this.

> Note that if you actually only want “inlines”, you can copy/paste micromark’s core (16 lines), and replace document() with text()

This seems like a very easy solution. I will try this soon and give you some feedback.

> Can you expand more on why you want to turn off “tokenizers” / constructs? 

I'm writing a Markdown App called [Rino](https://github.com/ocavue/rino). It provides a WYSIWYG way to write Markdown: 

![2020](https://user-images.githubusercontent.com/24715727/98541093-d6a76e80-22c9-11eb-85b7-7a378bb02f31.gif)

The image above should has the following DOM:

```html
<ul>
  <li>
    <p>
      <span>normal, </span>
      <span class="md-mark show">**</span>
      <strong>strong</strong>
      <span class="md-mark show">**</span>
      <span>, </span>
      <span class="md-mark">`</span>
      <code>code</code>
      <span class="md-mark">`</span>
    </p>
  </li>
</ul>
```

For a block element, I use regular expressions to replace the text while users input. For example, the user inputs `## `, then the editor will delete the text `## `, create a `<h2>` element,  and put the cursor into the `<h2>` element.

For an inline element, I use `<span>` to wrap those marks I want to hide. Then I can show these marks by adding CSS classes to them. By doing this, I can avoid editing the virtual DOM tree while showing or hiding the mark, which will make the editor faster. 

To add and remove HTML tag for inline content correctly, I need a way to parse a Markdown text into a serial of tokens and keep the origin position for each token (That's what mdast and micromark amaze me). Each time the user edits the inline text, I will re-parse the current paragraph, and edit the virtual DOM tree. This workflow is similar to a code editor with a syntax highlight feature. However, different from syntax highlight, I only need to parse inline content.


For a special example: When the user inputs `## `, current DOM is `<h2>{cursor}</h2>`. Then the user inputs `> hello`. The DOM should be `<h2>> hello{cursor}</h2>` since CommonMark doesn't allow a quota block inside a heading block. Therefore I have to ignore the `>` when parsing the inline content `> hello`.

I'm not sure if I describe my use case clearly. Ask me any questions or even suggestions.

**Comment by ocavue** [comment]
> Note that if you actually only want “inlines”, you can copy/paste micromark’s core (16 lines), and replace document() with text(). But: this will probably crash if there are for example blank lines in your markdown, because those can’t exist inline.

Based on my experience of using it for a few days, this method works very well. Thank you very much for your advice. @wooorm

**Comment by wooorm** [comment]
Glad to hear it @ocavue!

**Comment by wooorm** [comment]
If for some reason a certain construct does have to be turned off, that’s now supporting in micromark

**Comment by ocavue** [comment]
> If for some reason a certain construct does have to be turned off, that’s now supporting in micromark

Does `mdast-util-from-markdown` support this feature by updating `micromark` to the latest version?

**Comment by wooorm** [comment]
When it’s updated. Yeah. Working through all extensions now

**Comment by wooorm** [comment]
But turning off constructs !== inline
