### ISSUE TITLE
unexpected backslash before star/underscore/strike

### ISSUE THREAD

**Issue by JeremyFan** [remarkjs/remark#581]
### Subject of the issue

unexpected backslash before star/underscore/strike

### Your environment

*   **OS**: macOS Mojave 10.14.5
*   **Packages**: remark-parse@9.0.0
*   **Env**: node@10.17.0; npm@6.11.3

### Steps to reproduce

source:
```
1. **好（ good ）**、**好（good）**、**好（good）**好（good）
2. 2 * 5 = 10
3. ![img_1.png](images/img_1.png)
4. ---line---
```

[codesandbox](https://codesandbox.io/s/remark-debug-forked-ecmlq?file=/src/index.js)

### Expected behavior
```
1. **好（ good ）**、**好（good）**、**好（good）**好（good）
2. 2 * 5 = 10
3. ![img_1.png](images/img_1.png)
4. ---line---
```

### Actual behavior

```
1.  **好（ good ）**、**好（good）**、\*\*好（good）\*\*好
2.  2 \* 5 = 10
3.  ![img\_1.png](images/img\_1.png)
4.  \---line---
```

**Comment by wooorm** [comment]
Those are used to escape characters that might otherwise turn into something else.
This is similar to how you can’t put, say, a slash or a quote in a JavaScript string: `'a'b\c'` doesn’t “work”, but `'a\'b\\c'` does.

Unfortunately, markdown is much more complex in when something breaks or not: for markdown escaping we’re only looking at the previous and the next character, not detecting whether there is an asterisk somewhere else in a paragraph.
So, yeah, you’re going to get escapes.
If you think there are particular escapes that could be smarter, issues / PRs are welcome in the source of the algorithm: [`mdast-util-to-markdown/lib/unsafe.js`](https://github.com/syntax-tree/mdast-util-to-markdown/blob/main/lib/unsafe.js)

**Comment by zdm** [comment]
But this problem is solved in `prettier`.

**Comment by zeitderforschung** [comment]
cant we just use do the fix within rehype parse?
